# Generated by Django 5.2.15 on 2026-07-06 10:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('public_id', models.CharField(max_length=255)),
                ('secure_url', models.URLField()),
                ('resource_type', models.CharField(default='image', max_length=20)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('folder', models.CharField(blank=True, max_length=255)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('format', models.CharField(blank=True, max_length=20)),
                ('document_type', models.CharField(choices=[('GST_CERTIFICATE', 'GST Certificate'), ('PAN_CARD', 'PAN Card'), ('FSSAI_LICENSE', 'FSSAI License'), ('SHOP_LICENSE', 'Shop License'), ('IDENTITY_PROOF', 'Identity Proof'), ('ADDRESS_PROOF', 'Address Proof'), ('OTHER', 'Other')], max_length=30)),
            ],
            options={
                'verbose_name': 'Shop Document',
                'verbose_name_plural': 'Shop Documents',
                'db_table': 'shop_documents',
            },
        ),
        migrations.CreateModel(
            name='ShopImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('public_id', models.CharField(max_length=255)),
                ('secure_url', models.URLField()),
                ('resource_type', models.CharField(default='image', max_length=20)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('folder', models.CharField(blank=True, max_length=255)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('format', models.CharField(blank=True, max_length=20)),
                ('image_type', models.CharField(choices=[('LOGO', 'Shop Logo'), ('BANNER', 'Shop Banner'), ('STOREFRONT', 'Storefront Photo'), ('GALLERY', 'Gallery')], default='GALLERY', max_length=20)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Shop Image',
                'verbose_name_plural': 'Shop Images',
                'db_table': 'shop_images',
            },
        ),
        migrations.CreateModel(
            name='ShopOwnerRegistrationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner_full_name', models.CharField(max_length=150)),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_phone_number', models.CharField(max_length=20)),
                ('owner_date_of_birth', models.DateField(blank=True, null=True)),
                ('shop_name', models.CharField(db_index=True, max_length=200)),
                ('business_type', models.CharField(choices=[('INDIVIDUAL', 'Individual / Proprietorship'), ('PARTNERSHIP', 'Partnership'), ('PRIVATE_LIMITED', 'Private Limited'), ('LLP', 'LLP'), ('OTHER', 'Other')], max_length=20)),
                ('shop_category', models.CharField(blank=True, max_length=100)),
                ('shop_description', models.TextField(blank=True)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('fssai_license_number', models.CharField(blank=True, max_length=30, null=True)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='India', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bank_account_holder_name', models.CharField(blank=True, max_length=150)),
                ('bank_account_number', models.CharField(blank=True, max_length=30)),
                ('bank_ifsc_code', models.CharField(blank=True, max_length=15)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Shop Owner Registration Request',
                'verbose_name_plural': 'Shop Owner Registration Requests',
                'db_table': 'shop_owner_registration_requests',
            },
        ),
    ]
