# Generated by Django 5.2.15 on 2026-07-06 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop_owner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopdocument',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopimage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopimage',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopownerregistrationrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopownerregistrationrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_shop_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopownerregistrationrequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopownerregistrationrequest',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_owner_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopimage',
            name='registration_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop_owner.shopownerregistrationrequest'),
        ),
        migrations.AddField(
            model_name='shopdocument',
            name='registration_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='shop_owner.shopownerregistrationrequest'),
        ),
        migrations.AddIndex(
            model_name='shopownerregistrationrequest',
            index=models.Index(fields=['status'], name='shop_owner__status_1494b9_idx'),
        ),
        migrations.AddIndex(
            model_name='shopownerregistrationrequest',
            index=models.Index(fields=['shop_name'], name='shop_owner__shop_na_56a3dd_idx'),
        ),
        migrations.AddIndex(
            model_name='shopimage',
            index=models.Index(fields=['registration_request', 'image_type'], name='shop_images_registr_92c1d0_idx'),
        ),
        migrations.AddIndex(
            model_name='shopdocument',
            index=models.Index(fields=['registration_request', 'document_type'], name='shop_docume_registr_2a8966_idx'),
        ),
    ]
