# Generated by Django 5.2.15 on 2026-07-06 10:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('identifier_attempted', models.CharField(help_text='Phone number or email used for this login attempt.', max_length=255)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('LOCKED', 'Locked')], db_index=True, max_length=10)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('device_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Login History',
                'verbose_name_plural': 'Login History',
                'db_table': 'login_history',
            },
        ),
    ]
